server:
  port: ${port:8082}
  error.whitelabel.enabled: false
  compression:
    enabled: true
    min-response-size: 102400000
    mime-types:
      - text/html
      - text/css
      - text/plain
      - text/xml
      - application/json
      - application/javascript
  servlet:
    context-path: /

spring:
  application.name: pinko-dir
  ldap:
    urls: ldap://10.1.16.126:389
    base: OU=Users,OU=504,OU=Clients,DC=504dn,DC=aossia,DC=com
    username: CN=ldap.voice,OU=_Service Objects,DC=aossia,DC=com
    password: 6QNqw8xWbT

directory:
  instance: bertrange
  hostname: 10.67.33.66
  proto: http
  type: microsoft
  phoneProperty: ipPhone